//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclarationQuesiton
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeclarationQuesiton()
        {
            this.DeclarationAnswers = new HashSet<DeclarationAnswer>();
            this.ReferenceDeclarationAnswers = new HashSet<ReferenceDeclarationAnswer>();
            this.ScholarDeclarationAnswers = new HashSet<ScholarDeclarationAnswer>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public int QuestionOrder { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int ContactTypeId { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeclarationAnswer> DeclarationAnswers { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceDeclarationAnswer> ReferenceDeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarDeclarationAnswer> ScholarDeclarationAnswers { get; set; }
    }
}
