//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.ContactDocumentAggreements = new HashSet<ContactDocumentAggreement>();
            this.ContactDocumentAggreements1 = new HashSet<ContactDocumentAggreement>();
            this.ContactTypeRels = new HashSet<ContactTypeRel>();
            this.ContactTypeRels1 = new HashSet<ContactTypeRel>();
            this.DeclarationAnswers = new HashSet<DeclarationAnswer>();
            this.DeclarationAnswers1 = new HashSet<DeclarationAnswer>();
            this.DeclarationQuesitons = new HashSet<DeclarationQuesiton>();
            this.DeclarationQuesitons1 = new HashSet<DeclarationQuesiton>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.DocumentInstances = new HashSet<DocumentInstance>();
            this.DocumentInstances1 = new HashSet<DocumentInstance>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.RefenceResults = new HashSet<RefenceResult>();
            this.RefenceResults1 = new HashSet<RefenceResult>();
            this.References = new HashSet<Reference>();
            this.References1 = new HashSet<Reference>();
            this.ReferenceDeclarationAnswers = new HashSet<ReferenceDeclarationAnswer>();
            this.ReferenceDeclarationAnswers1 = new HashSet<ReferenceDeclarationAnswer>();
            this.ReferenceFileUploads = new HashSet<ReferenceFileUpload>();
            this.ReferenceFileUploads1 = new HashSet<ReferenceFileUpload>();
            this.ScholarBankAccounts = new HashSet<ScholarBankAccount>();
            this.ScholarBankAccounts1 = new HashSet<ScholarBankAccount>();
            this.ScholarchipGiverCreditCardInfoes = new HashSet<ScholarchipGiverCreditCardInfo>();
            this.ScholarchipGiverCreditCardInfoes1 = new HashSet<ScholarchipGiverCreditCardInfo>();
            this.ScholarchipGiverCreditCardProvisinings = new HashSet<ScholarchipGiverCreditCardProvisining>();
            this.ScholarchipGiverCreditCardProvisinings1 = new HashSet<ScholarchipGiverCreditCardProvisining>();
            this.ScholarchipGiverSelectScholars = new HashSet<ScholarchipGiverSelectScholar>();
            this.ScholarchipGiverSelectScholars1 = new HashSet<ScholarchipGiverSelectScholar>();
            this.ScholarDeclarationAnswers = new HashSet<ScholarDeclarationAnswer>();
            this.ScholarDeclarationAnswers1 = new HashSet<ScholarDeclarationAnswer>();
            this.ScholarFileUploads = new HashSet<ScholarFileUpload>();
            this.ScholarFileUploads1 = new HashSet<ScholarFileUpload>();
            this.ScholarReceives = new HashSet<ScholarReceive>();
            this.ScholarReceives1 = new HashSet<ScholarReceive>();
            this.ScholarRequests = new HashSet<ScholarRequest>();
            this.ScholarRequests1 = new HashSet<ScholarRequest>();
            this.ScholarRequestSchoolInfoes = new HashSet<ScholarRequestSchoolInfo>();
            this.ScholarRequestSchoolInfoes1 = new HashSet<ScholarRequestSchoolInfo>();
        }
    
        public int Id { get; set; }
        public int ContactId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactDocumentAggreement> ContactDocumentAggreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactDocumentAggreement> ContactDocumentAggreements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactTypeRel> ContactTypeRels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactTypeRel> ContactTypeRels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeclarationAnswer> DeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeclarationAnswer> DeclarationAnswers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeclarationQuesiton> DeclarationQuesitons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeclarationQuesiton> DeclarationQuesitons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentInstance> DocumentInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentInstance> DocumentInstances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefenceResult> RefenceResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefenceResult> RefenceResults1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> References1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceDeclarationAnswer> ReferenceDeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceDeclarationAnswer> ReferenceDeclarationAnswers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceFileUpload> ReferenceFileUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceFileUpload> ReferenceFileUploads1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarBankAccount> ScholarBankAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarBankAccount> ScholarBankAccounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverCreditCardInfo> ScholarchipGiverCreditCardInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverCreditCardInfo> ScholarchipGiverCreditCardInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverCreditCardProvisining> ScholarchipGiverCreditCardProvisinings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverCreditCardProvisining> ScholarchipGiverCreditCardProvisinings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverSelectScholar> ScholarchipGiverSelectScholars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverSelectScholar> ScholarchipGiverSelectScholars1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarDeclarationAnswer> ScholarDeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarDeclarationAnswer> ScholarDeclarationAnswers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarFileUpload> ScholarFileUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarFileUpload> ScholarFileUploads1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarReceive> ScholarReceives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarReceive> ScholarReceives1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarRequest> ScholarRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarRequest> ScholarRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarRequestSchoolInfo> ScholarRequestSchoolInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarRequestSchoolInfo> ScholarRequestSchoolInfoes1 { get; set; }
    }
}
