//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reference()
        {
            this.RefenceResults = new HashSet<RefenceResult>();
            this.ReferenceDeclarationAnswers = new HashSet<ReferenceDeclarationAnswer>();
            this.ReferenceFileUploads = new HashSet<ReferenceFileUpload>();
        }
    
        public int Id { get; set; }
        public int ScholarRequestContactId { get; set; }
        public int ReferenceContactId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int ReferenceContactTypeId { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int DistrictId { get; set; }
        public string RegisterNumber { get; set; }
        public string TeacherUniversity { get; set; }
        public string TeacherUniversityFaculty { get; set; }
        public string TeacherUniversityFacultyDepartment { get; set; }
        public string TeacherHighSchool { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Contact Contact1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefenceResult> RefenceResults { get; set; }
        public virtual ReferenceContactType ReferenceContactType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceDeclarationAnswer> ReferenceDeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceFileUpload> ReferenceFileUploads { get; set; }
    }
}
