//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipGiver
    {
        public int Id { get; set; }
        public int ScholarshipGiverContactId { get; set; }
        public int ScholarshipGiverApprovalStatusId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ScholarchipGiverApprovalStatu ScholarchipGiverApprovalStatu { get; set; }
    }
}
