//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        public int Id { get; set; }
        public int ScholarshipOwnerContactId { get; set; }
        public string ScholarshipName { get; set; }
        public string ScholarshipDescription { get; set; }
        public int YearId { get; set; }
        public int SeasonId { get; set; }
        public int GiverCount { get; set; }
        public decimal GiverMonthlyDonateAmount { get; set; }
        public int ScholarCount { get; set; }
        public decimal ScholarDonateAmount { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Season Season { get; set; }
        public virtual Year Year { get; set; }
    }
}
