//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScholarRequest()
        {
            this.ReferenceDeclarationAnswers = new HashSet<ReferenceDeclarationAnswer>();
            this.ScholarchipGiverSelectScholars = new HashSet<ScholarchipGiverSelectScholar>();
            this.ScholarDeclarationAnswers = new HashSet<ScholarDeclarationAnswer>();
            this.ScholarFileUploads = new HashSet<ScholarFileUpload>();
            this.ScholarRequestSchoolInfoes = new HashSet<ScholarRequestSchoolInfo>();
        }
    
        public int Id { get; set; }
        public int ScholarContactId { get; set; }
        public System.DateTime RequestTime { get; set; }
        public int YearId { get; set; }
        public int SeasonId { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int DistrictId { get; set; }
        public int ScholarRequestStatusId { get; set; }
        public int ScholarRequestRejectedReasonId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceDeclarationAnswer> ReferenceDeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarchipGiverSelectScholar> ScholarchipGiverSelectScholars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarDeclarationAnswer> ScholarDeclarationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarFileUpload> ScholarFileUploads { get; set; }
        public virtual ScholarRequestRejectReason ScholarRequestRejectReason { get; set; }
        public virtual ScholarRequestStatu ScholarRequestStatu { get; set; }
        public virtual Season Season { get; set; }
        public virtual Year Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarRequestSchoolInfo> ScholarRequestSchoolInfoes { get; set; }
    }
}
