//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarchipGiverCreditCardInfo
    {
        public int Id { get; set; }
        public int ScholarshipGiverContactId { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardNumber { get; set; }
        public short CVC2 { get; set; }
        public short ExpaireYear { get; set; }
        public short ExpaireMonth { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
    }
}
